# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'AFNetworking'
pod 'MJExtension'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'Masonry'
pod 'MJRefresh’
pod 'CYLTableViewPlaceHolder'